### ISSUE TITLE
No wheel released in PyPi repo

### ISSUE THREAD

**Issue by ankostis** [vinci1it2000/formulas#1]
Currently no wheel has been published in [PyPi repo](https://pypi.python.org/pypi/formulas) - only sources.
What you have been using to rlease your projects is outdated!

Always use these commands when releasing a project:

```bash
python setup.py sditst bdist_wheel ## Build sources and whl into ./dist/ dir
twine upload dist/*                ## Release built wheel
```

**Comment by vinci1it2000** [comment]
Done. https://pypi.python.org/pypi/formulas/0.0.5
