### ISSUE TITLE
Shapeless array returned from IRR calculation

### ISSUE THREAD

**Issue by ecatkins** [vinci1it2000/formulas#10]
With the move to 0.0.8, constructing an IRR function from an excel expression e.g. `=IRR(A1:A3)` and then trying to utilise that function produces a shapeless array. It contains the correct answer, but A) it shouldn't be an array B) because it is shapeless you can't index in to retrieve the answer.

Currently hacking around it for my own purposes by doing something like:
```
result = constructed_irr_function(*args)
if type(result) == formulas.formulas.Array and not result.shape:
    result = result.reshape(1,)[0]
```
But I will try to look into the underlying reason over the next couple of days.

**Comment by vinci1it2000** [comment]
I have fixed. Now it is returning an array with shape `(1, 1)`.
