### ISSUE TITLE
Combination with IFERROR and VLOOKUP from another sheet does not return a correct value

### ISSUE THREAD

**Issue by proexcuse** [vinci1it2000/formulas#103]
Hi,

formulas.Parser() cannot handle the combination with IFERROR and VLOOKUP from another sheet. It does not get a correct value on the excel file. 

This bug was originally found in openpyxl. To reproduce  the bug, see the URL below.
https://foss.heptapod.net/openpyxl/openpyxl/-/issues/1715

**Comment by vinci1it2000** [comment]
Can you share the input file?
