### ISSUE TITLE
Question: How to ignore invalid formula

### ISSUE THREAD

**Issue by masykur8d** [vinci1it2000/formulas#108]
I am using the formulas library and come across the invalid formula error. I have read the documentation and the other issues here but I did not found any relevant answer.]

The error looks like this:

`FormulaError: ('Not a valid formula:\n%s', '=IFERROR(IF(COUNTIF(F5,"*中*"),"-",IF(U5>=G5,IF(MATCH(M5,【車検A軍】ラベルリスト!$A:$A,0)-1=0,INDEX(【車検A軍】ラベルリスト!$A:$A,MATCH(M5,【車検A軍】ラベルリスト!$A:$A,0)),INDEX(【車検A軍】ラベルリスト!$A:$A,MATCH(M5,【車検A軍】ラベルリスト!$A:$A,0)-1)),F5)),"error")')`

Is there a way to ignore the error?

the code looks like this:
```
xl_model = formulas.ExcelModel().loads(path2).finish()
xl_model.calculate()
xl_model.write(dirpath=path1)
```

**Comment by vinci1it2000** [comment]
Can you share the input file?

**Comment by vinci1it2000** [comment]
Special characters【】 broke the parser. Use normal characters.
