### ISSUE TITLE
Possible to implement TEXT() and VALUE() functions?

### ISSUE THREAD

**Issue by viguice** [vinci1it2000/formulas#110]
I have the following function '=TEXT(VALUE(A1),"00")' where A1 can be a number or a text. The result is always a text using the correct formatting:
A1 -> Result
1 -> 01
10 ->10
'5 -> 05
test -> #VALUE! 

The value and text functions don't work as I get #NAME? value for this formula. Can you add them?

Thanks a lot,

Cédric

**Comment by vinci1it2000** [comment]
I have implemented the TEXT and VALUE functions. They will be included in the next release.
