### ISSUE TITLE
Regex doesn't match when sheet has a double quotation in its name (").

### ISSUE THREAD

**Issue by jonathanpedersen** [vinci1it2000/formulas#113]
**Describe the bug**
I have a sheet title with the word "Paper" in it. When I load it using the follow code...

xl_model = formulas.ExcelModel().loads(filepath)

it fails with the error...

 for k, v in _re_range.match(ref).groupdict().items():
AttributeError: 'NoneType' object has no attribute 'groupdict'

Suggesting that the _re_range.match(ref) returns None, suggesting the regex doesn't match.

When I remove the double quotations from the sheet's title, it works flawlessly.

**To Reproduce**
I would like to avoid this if possible, as the excel spreadsheet contains sensitive data that would be hard to remove.

**Expected behavior**
Normal loading.

**Desktop (please complete the following information):**
 - OS: macOS Monterey
 - Version 12.2

**Additional context**

**Comment by vinci1it2000** [comment]
Fixed it will be included in the next release.
