### ISSUE TITLE
Error in ExcelModel().loads(filename) - 'DefinedNameDict' object has no attribute 'definedName' (Python 3.9)

### ISSUE THREAD

**Issue by horkah** [vinci1it2000/formulas#114]
**Describe the bug**
The `test_excel.py` script provided here on Git fails to complete without error.

**To Reproduce**
I downloaded (6feb2023) the files `test_excel.py` and `test_files` from here:
https://github.com/vinci1it2000/formulas/tree/master/test

I use python 3.9.16 and installed the missing required packages (`dill`, `schedula`, `formulas[all]`)

I appended the following lines at the end of `test_excel.py`:
```
[...]
if __name__ == '__main__':
    print("hello world")
    t = TestExcelModel()
    t.setUp()
    t.test_excel_model()
    exit()
```

and receive the following error message:
```
hello world

[info] test_excel_model: Loading excel-model.
Traceback (most recent call last):
  File "[...]\PycharmProjects\[...]\test_excel.py", line 285, in <module> t.test_excel_model()
  File "[...]\PycharmProjects\[...]\test_excel.py", line 112, in test_excel_model xl_mdl.loads(self.filename)
  File "[...]\PycharmProjects\[...]\venv\lib\site-packages\formulas\excel\__init__.py", line 108, in loads self.load(filename)
  File "[...]\PycharmProjects\[...]\venv\lib\site-packages\formulas\excel\__init__.py", line 112, in load book, context = self.add_book(filename)
  File "[...]\PycharmProjects\[...]\venv\lib\site-packages\formulas\excel\__init__.py", line 188, in add_book data['references'] = self.add_references(book, context=context)
  File "[...]\PycharmProjects\[...]\venv\lib\site-packages\formulas\excel\__init__.py", line 93, in add_references for n in book.defined_names.definedName:
AttributeError: 'DefinedNameDict' object has no attribute 'definedName'

Process finished with exit code 1
```

**Expected behavior**
The `test_excel.py` provided here with the repository is expected to work under Python 3.9 with all required packages installed.

**Desktop:**
 - OS: Windows 11
 - Python 3.9.16

**Comment by michaelkryukov** [comment]
I've had same issue – looks like it's because of new version of `openpyxl`. Pinning version to `openpyxl>=3.0.7,<3.1.0` seems to help. I think `formulas` should be updated with recent recommendations from `openpyxl` on how to interact with defined names.

**Comment by maffblaster** [comment]
Anyone know how difficult it would be to fix this bug? I am also in the same boat on python 3.11.x:

`'DefinedNameDict' object has no attribute 'definedName'`

I am using openpyxl>=3.1.0 since I need the newly added Custom Data Properties functionality, so I can't downgrade to an older version.

@vinci1it2000, thanks for the awesome work!

**Comment by maffblaster** [comment]
> I've had same issue – looks like it's because of new version of `openpyxl`. Pinning version to `openpyxl>=3.0.7,<3.1.0` seems to help. I think `formulas` should be updated with recent recommendations from `openpyxl` on how to interact with defined names.

What are these recent recommendations?

**Comment by michaelkryukov** [comment]
I'm not sure, but docs should contain needed informations (something like [that](https://openpyxl.readthedocs.io/en/stable/defined_names.html#defined-names)).

**Comment by MizsakPeterEcon** [comment]
I'm facing the same issue and did some digging in the OpenPyXl repository:

In the release note of `openpyxl 3.1.0` I found that defined names were restructured: [Issue link](https://foss.heptapod.net/openpyxl/openpyxl/-/issues/1864)
([commit of the change](https://foss.heptapod.net/openpyxl/openpyxl/-/commit/364b594f2fea7bf1919f089c5c4771edd1cee090))

`DefinedNameList` is replaced by `DefinedNameDict` when accessing from the `worksheet` object.

In `openpyxl 3.0.10`:
```python
print(type(workbook.defined_names))
>>> <class 'openpyxl.workbook.defined_name.DefinedNameList'>
```

In `openpyxl 3.1.0`:
```python
print(type(workbook.defined_names))
>>> <class 'openpyxl.workbook.defined_name.DefinedNameDict'>
```

---

An other change that might be relevant in the removal of `formula_attributes` attribute. (see  [release notes](https://openpyxl.readthedocs.io/en/stable/changes.html?highlight=formula%20attributes#id4))
Here the `array_formulae` property can be used instead. ([commit of the change](https://foss.heptapod.net/openpyxl/openpyxl/-/commit/b71b6ba667e9fcf8de3f899382d446626e55970c))

@vinci1it2000 I've never contributed to any open source project, but with some assistance I can try to make a PR to fix these issues.

**Comment by maffblaster** [comment]
Looks like it is getting fixed in the next release! Thank you, @vinci1it2000!
