### ISSUE TITLE
How to get type of output from OperatorArray?

### ISSUE THREAD

**Issue by jstray** [vinci1it2000/formulas#12]
I've run into a change from `formulas 0.0.7` to `0.0.10` which is causing me trouble. The result type no longer seems to depend on the input type, or really have a type at all.

Old: multiplication on `int` returned `int`
```
$ pip list | grep formulas
formulas                 0.0.7    
$ python3
Python 3.6.2 |Continuum Analytics, Inc.| (default, Jul 20 2017, 13:14:59) 
[GCC 4.2.1 Compatible Apple LLVM 6.0 (clang-600.0.57)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> from formulas import Parser
>>> code = Parser().ast('=B1*2')[1].compile()
>>> out = code(10)
>>> out
20
>>> type(out)
<class 'int'>
>>> 
```

New: multiplication on `int` returns `OperatorArray`
```
$ pip list | grep formulas
formulas                 0.0.10    
$ python3
Python 3.6.2 |Continuum Analytics, Inc.| (default, Jul 20 2017, 13:14:59) 
[GCC 4.2.1 Compatible Apple LLVM 6.0 (clang-600.0.57)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> from formulas import Parser
>>> code = Parser().ast('=B1*2')[1].compile()
>>> out = code(10)
>>> out
OperatorArray(20.0, dtype=object)
>>> type(out)
<class 'formulas.functions.operators.OperatorArray'>
```

The output seems to be `OperatorArray` regardless of whether the actual output is int, float, or string. Is there any way to recover the result type from the OperatorArray?

Thanks for all your work on this project. We're very happy to be using it for [Workbench](https://github.com/CJWorkbench/cjworkbench).

**Comment by vinci1it2000** [comment]
The OperatorArray is a numpy array. In this case it is shapeless. 
```
>>> out.shape
()
```
Hence, to retrieve the value and its type you can use the `tolist` method. 
```
>>> type(out.tolist())
float
```
In the current version of formulas all numbers are converted as `float`, so if you want to check if it is an integer you can invoke the method `is_integer`.
```
>>> out.tolist().is_integer()
True
```

**Comment by jstray** [comment]
Thanks. Are there any Excel formulas which can return arrays of values?

Also I'd be happy to write some basic docs on using this library.

**Comment by vinci1it2000** [comment]
Yes. All functions that use [wrap_ufunc](https://github.com/vinci1it2000/formulas/blob/master/formulas/functions/__init__.py#L155) return an [Array](https://github.com/vinci1it2000/formulas/blob/master/formulas/functions/__init__.py#L40) as value. About the docs you are welcome. If you write something I can review it.
