### ISSUE TITLE
General info

### ISSUE THREAD

**Issue by ShieldTrade** [vinci1it2000/formulas#120]
Hi, 

Where can I find Excel formulas already implemented?

Is it possible to calculate a single cell or a range?

Thankyou

**Comment by vinci1it2000** [comment]
1. You can install it using the command `pip install formulas` or if you have conda installed, `conda install -c conda-forge formulas`.
2. You can load a partial Excel model from the output cells or ranges; you can use the `from_ranges` method of the `ExcelModel`:

```
    >>> xl = formulas.ExcelModel().from_ranges(
    ...     "'[excel.xlsx]DATA'!C2:D2" % fpath,  # Output range.
    ...     "'[excel.xlsx]DATA'!B4" % fpath,  # Output cell.
    ... )
```
If you want to load the Excel once and use it interactively, you can specify the `outputs` when calculating so it will calculate only the needed results.
