### ISSUE TITLE
Contribuitions

### ISSUE THREAD

**Issue by dtorres-sf** [vinci1it2000/formulas#14]
Hi @vinci1it2000,

I am evaluating formulas and in the process added a dozen or so of excel functions. Should I just open a PR, are there any guidelines to contribuitions?

Also, when adding ROW() which gets the current cells row number I wasn't sure the best way to do it. I added the ability to bind functions which would in turn pass in the Cell instance as the first argument which allowed me to get the range. Not being familiar with the code, I wasn't sure if there was a better way to do it.

**Comment by vinci1it2000** [comment]
I wrote a simple guideline (6ed4522) on how to implement and submit a new excel function or a group.

I implemented ROW function. This is a simple example how to use:

    import formulas
    func = formulas.Parser().ast('=ROW()')[1].compile(**{formulas.CELL: formulas.Ranges().push('A3')})
    func()
    3

Or if you pass a reference value (i.e., A1) then you have to pass a range:

    import formulas
    func = formulas.Parser().ast('=ROW(A1)')[1].compile()
    func(formulas.Ranges().push('A1'))
    1
    func(formulas.Ranges().push('A2'))
    2
