### ISSUE TITLE
How to add a function easily?

### ISSUE THREAD

**Issue by demonye** [vinci1it2000/formulas#15]
I have an excel file with some customized functions written in vba, I'm trying to map them to python function. After a quick looking at the formulas codes, I guess I could do something like

```
class MyBuilder(formulas.builder.AstBuilder):
    def __init__(self, *args, **kwargs):
        dsp = schedula.Dispatcher(raises=True)
        dsp.add_function('func1', lambda x: x+1)
        kwargs['dsp'] = dsp
        super(MyBuilder, self).__init__(*args, **kwargs)

formulas.parser.Parser.ast_builder = MyBuilder

```

But looks it isn't as easy as that. @vinci1it2000 really appreciate if you could give me some hints.

**Comment by vinci1it2000** [comment]
An example how to add a custom function to the formula parser is the following:

    import formulas
    formulas.FUNCTIONS['MYFUNC'] = lambda x, y: 1 + y + x
    func = formulas.Parser().ast('=MYFUNC(1, 2)')[1].compile()
    func()
    4
