### ISSUE TITLE
IF function evaluates both true and false cases

### ISSUE THREAD

**Issue by lucasbalves** [vinci1it2000/formulas#150]
**Describe the bug**
I'm using formulas in a project, particularly because of its support for custom functions. It works really well for the most part, but I've noticed that if a formula contains an IF statement, the library evaluates both the true and false branches. In most cases, it's not a big deal, but sometimes I use the IF statement to handle expressions that can raise an exception, so I put them in the false branch but they are evaluated regardless

**To Reproduce**
```python
import formulas

FUNCTIONS = formulas.get_functions()

def sum_nums(x,y):
    raise Exception("Sum nums was called incorrectly")
    return x + y
    
def multiply_nums(x,y):
    return x * y

FUNCTIONS["SUM_NUMS"] = sum_nums
FUNCTIONS["MULTIPLY_NUMS"] = multiply_nums

formula_str = "=IF(TRUE, MULTIPLY_NUMS(3,4), SUM_NUMS(1,2))"

func = formulas.Parser().ast(formula_str)[1].compile()

print(float(func()))

```

**Expected behavior**
The false branch should not be evaluated, similar to how it works in MS Excel. For example:

=IF(TRUE, 1, 1/0) => should return 1 without evaluating the division by zero.

**Desktop (please complete the following information):**
 - Windows 11
 - Python 3.11.1
 - formulas 1.28

**Comment by vinci1it2000** [comment]
To solve this issue, you can wrap your custom function using the utility function `wrap_func` from `formulas.functions`. This will ensure the function behaves correctly in the context of an IF statement.

If you want to transform the function into a vectorial function, you should use `wrap_ufunc` instead.

Here's how you can apply it to your example:
```python
import formulas
from formulas.functions import wrap_func  # or wrap_ufunc for vectorial functions

FUNCTIONS = formulas.get_functions()

def sum_nums(x, y):
    raise Exception("Sum nums was called incorrectly")
    
def multiply_nums(x, y):
    return x * y

FUNCTIONS["SUM_NUMS"] = wrap_func(sum_nums)
FUNCTIONS["MULTIPLY_NUMS"] = wrap_func(multiply_nums)

formula_str = "=IF(TRUE, MULTIPLY_NUMS(3,4), SUM_NUMS(1,2))"

func = formulas.Parser().ast(formula_str)[1].compile()

print(float(func()))  # 12.0
```

**Comment by dberardo-com** [comment]
May I ask why wrapping the function is necessary and it is not the default behavior?

Is there any other advantage of wrapping functions other than this behavior in if statement?

Why wouldn't we want to wrap just any custom function then?

**Comment by dberardo-com** [comment]
> May I ask why wrapping the function is necessary and it is not the default behavior?
> 
> Is there any other advantage of wrapping functions other than this behavior in if statement?
> 
> Why wouldn't we want to wrap just any custom function then?

please let us know @vinci1it2000  ;)

**Comment by dberardo-com** [comment]
btw i dont know if this is related to this issue, but i would like to define a formula that gets lazily evaluated such as "NOW()" which should obviously not be cached.

i have noticed that if i did NOW(A1) this would not be cached because of course A1 can change at computation time, but NOW() will be cached. is there a way to prevent this ? should one use the wrapper as above ?

cheers

**Comment by dberardo-com** [comment]
i have moved the last question into a new issue: https://github.com/vinci1it2000/formulas/issues/165
