### ISSUE TITLE
Comparison with Pycel

### ISSUE THREAD

**Issue by Immortalin** [vinci1it2000/formulas#17]
How does this compare to Pycel feature-wise?
https://github.com/dgorissen/pycel

**Comment by vinci1it2000** [comment]
Feature | pycel | formulas
-- | -- | --
Compilation | The initial compilation uses COM   server, so an instance of Excel must be available and it has to run in   Windows. | python code with lightweight 45M   dependencies (see #13).
Implemented Excel   Functions | ~50 | ~100
Accuracy | Agrees with Excel up to 5 decimal places. | Replicate exactly the Excel results.
Cycles | not supported | supported
Cell references | not supported | supported
Excel Errors | not supported | supported
VBA code | not supported | not supported

Performances to compile and execute the `test_files/excel.xlsx`:

Phase | pycel | formulas
-- | -- | --
compilation | Slower (0.434 sec) | Faster (0.019 sec)
execution | Faster (0.000022 sec) | Slower (0.001381 sec)
overall | formulas is 21 times faster then pycel to compile   and execute the excel code.

If you want to contribute to the features list, you are welcome.
