### ISSUE TITLE
excel  formula eg: '=IF(C64>2,0.6,IF(AND(C64>0,C64<=2),0.5,)) ' error

### ISSUE THREAD

**Issue by coderEvolve** [vinci1it2000/formulas#22]
Program execution encountered this formula, the program reported an error

1. xl_model = ExcelModel().loads(filename).finish()
2. xl_model.calculate()
3. See error
![default](https://user-images.githubusercontent.com/38391014/49146046-3bb36500-f33c-11e8-9e26-cc712585cfee.png)

**Comment by vinci1it2000** [comment]
AND function is now implemented e756b79a03d.
