### ISSUE TITLE
Change a value of an input cell

### ISSUE THREAD

**Issue by codekiln** [vinci1it2000/formulas#23]
Cool library! Many thanks.

**Is your feature request related to a problem? Please describe.**
My use case is a workbook with a sub-model that has 10-20 inputs and 5-10 outputs, and I'd like to write a python program to optimize the outputs by changing the inputs. 
The [docs describe how to retrieve a calculation from an Excel sub-model](https://formulas.readthedocs.io/en/stable/doc.html#excel-workbook), but there is currently no indication of whether the library can allow changing the inputs to an excel sub-model. 

**Describe the solution you'd like**
If this feature is already supported, I'd like it if it were documented with an example. If the feature is not already supported, I'd like it to be mentioned in the examples page stating that it is not currently supported.

**Comment by vinci1it2000** [comment]
Thanks. 

Yes this feature is supported. 

**formulas** is builded on top of another library [schedula](https://schedula.readthedocs.io/en/master/doc.html). When you load an excel file a [Dispatcher](https://schedula.readthedocs.io/en/master/_build/schedula/dispatcher/schedula.dispatcher.Dispatcher.html#schedula.dispatcher.Dispatcher) is compiled. 

```python
>>> import formulas
>>> fpath = 'file.xlsx'  
>>> xl_model = formulas.ExcelModel().loads(fpath).finish()
>>> xl_model.dsp
<schedula.dispatcher.Dispatcher at ...>
```

The method `calculate` of the `ExcelModel` invoke the method [dispatch](https://schedula.readthedocs.io/en/master/_build/schedula/dispatcher/Dispatcher/schedula.dispatcher.Dispatcher.dispatch.html) of the `Dispatcher`:

https://github.com/vinci1it2000/formulas/blob/0adf497f616dcccd183f33e1fc825c54172953d7/formulas/excel.py#L35-L42

To retrive the data node ids (i.e., cell references) that you can pass as input and or those with a default value you can type the following:
```python
>>> sorted(xl_model.dsp.data_nodes)  # To retrive the data node ids that you can pass as input.
["'[EXCEL.XLSX]DATA'!A1", "'[EXCEL.XLSX]DATA'!A2", "'[EXCEL.XLSX]DATA'!A3", 
 "'[EXCEL.XLSX]DATA'!A3:A4", "'[EXCEL.XLSX]DATA'!A4", "'[EXCEL.XLSX]DATA'!B1",
 "'[EXCEL.XLSX]DATA'!B2", "'[EXCEL.XLSX]DATA'!B3", "'[EXCEL.XLSX]DATA'!B4",
 "'[EXCEL.XLSX]DATA'!C1", "'[EXCEL.XLSX]DATA'!C2", "'[EXCEL.XLSX]DATA'!C3",
 "'[EXCEL.XLSX]DATA'!C4"]
>>> sorted(xl_model.dsp.default_values)  # To retrive the data node ids that have a default value.
["'[EXCEL.XLSX]DATA'!A1", "'[EXCEL.XLSX]DATA'!A2", "'[EXCEL.XLSX]DATA'!A3",
 "'[EXCEL.XLSX]DATA'!A4", "'[EXCEL.XLSX]DATA'!B1", "'[EXCEL.XLSX]DATA'!C1"]
```
This method allow to overwrite the default inputs that are defined by the excel file and to impose some value to a specific cell. To execute the model:
```python
>>> sol = xl_model.calculate(
...     inputs={
...         "'[EXCEL.XLSX]DATA'!A2": 3,  # To overwrite the default value.
...         "'[EXCEL.XLSX]DATA'!B3": 1  # To impose a value to the `B3` cell.
...     }, 
...     outputs=["'[EXCEL.XLSX]DATA'!C2", "'[EXCEL.XLSX]DATA'!C4"] # To define the outputs that you want to calculate.
... )
>>> sol  # It is the full solution with all cell results. 
Solution([("'[EXCEL.XLSX]DATA'!A2", <Ranges>('[EXCEL.XLSX]DATA'!A2)=[[3]]),
          ("'[EXCEL.XLSX]DATA'!A3", <Ranges>('[EXCEL.XLSX]DATA'!A3)=[[6]]),
          ("'[EXCEL.XLSX]DATA'!B3", <Ranges>('[EXCEL.XLSX]DATA'!B3)=[[1]]),
          ("'[EXCEL.XLSX]DATA'!B2", <Ranges>('[EXCEL.XLSX]DATA'!B2)=[[9.0]]),
          ("'[EXCEL.XLSX]DATA'!C2", <Ranges>('[EXCEL.XLSX]DATA'!C2)=[[9.0]]),
          ("'[EXCEL.XLSX]DATA'!C4", <Ranges>('[EXCEL.XLSX]DATA'!C4)=[[1.0]])])
```

If you need to build a single function out of an excel model with fixed inputs and outputs ids, I suggest the `compile` method of the `ExcelModel` that returns a [DispatchPipe](https://schedula.readthedocs.io/en/master/_build/schedula/utils/dsp/schedula.utils.dsp.DispatchPipe.html#schedula.utils.dsp.DispatchPipe). This is a function where the inputs and outputs are defined by the data node ids (i.e., cell references).
```python
>>> func = xl_model.compile(
...     inputs=[
...         "'[EXCEL.XLSX]DATA'!A2",  # First argument of the function.
...         "'[EXCEL.XLSX]DATA'!B3"   # Second argument of the function.
...     ], # To define function inputs.
...     outputs=["'[EXCEL.XLSX]DATA'!C2", "'[EXCEL.XLSX]DATA'!C4"] # To define function outputs.
... )
>>> func
<schedula.utils.dsp.DispatchPipe at ...>
```

Now you have a simple function that you can use in your optimization script. To retrive the data you can see the following example:
```python
>>> [v.value[0, 0] for v in func(3, 1)]
[9.0, 1.0]
>>> [v.value[0, 0] for v in func(3, 3)]
[3.0, 27.0]
```

**Comment by codekiln** [comment]
Many, many thanks, this is a very good explanation. I will experiment with this and post back here if there's any follow up question.

**Comment by KhabibulinRinat** [comment]
Thanks, the documentation on this page is excellent!

**Comment by vinci1it2000** [comment]
I added in the documentation the example.

I think that there are not more questions for the moment. Hence, I’m closing the issue. In case you can reopen it.
