### ISSUE TITLE
Nested functions will return "#VALUE!" and error parent functions

### ISSUE THREAD

**Issue by martmists** [vinci1it2000/formulas#28]

**Comment by vinci1it2000** [comment]
@martmists Can you add the code to reproduce the error?

**Comment by owinebar** [comment]
I am seeing a phenomenon somewhat like this while trying to add some custom functions.  It looks like there is some disconnect in hooking up the nodes of the main graph to the dispatcher pipe wrapped by a CellWrapper object.  The main function in the cell formula is receiving #value errors corresponding to the function calls being supplied as parameters.  I am able to manually construct a call to the cell wrapper function that supplies the values of the cells identified by the CellWrapper.inputs attribute from a solution object for the ExcelModel 
I haven't figured out exactly where the disconnect is happening yet.

**Comment by owinebar** [comment]
This only became apparent after I instrumented the custom functions to print their inputs.  The ExcelModel calculate method showed the outer function getting invoked but not the functions for the subexpressions.  When I explicitly invoked the CellWrapper function with the values of the input cells, the subexpression functions were definitely invoked as the inputs were printed.
