### ISSUE TITLE
Cannot install on python2.7. "Command "python setup.py egg_info" failed with error code 1"

### ISSUE THREAD

**Issue by nehagupta93** [vinci1it2000/formulas#29]
I ran `pip install formulas[all]`
And got the following output:
`Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-G63Y__/formulas/setup.py", line 62, in <module>
        proj_ver = read_project_version()
      File "/tmp/pip-install-G63Y__/formulas/setup.py", line 26, in read_project_version
        exec(fd.read(), fglobals)  # To read __version__
      File "<string>", line 0
    SyntaxError: encoding declaration in Unicode string
    
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-install-G63Y__/formulas/`

Things that I have tried which did not work (with and without sudo access, in and outside the virtual environment):

- `sudo pip install --upgrade setuptools`
- `sudo apt-get install libmysqlclient-dev`
- `pip install --upgrade pip`
- `pip install formulas`

I also tried installing it by cloning the repository and running the _setup.py_ file.

The error does not occur with python3. My project only runs on 2.7. Does this repository only support python3?

**Comment by vinci1it2000** [comment]
I'm sorry but this library supports for the moment support the following python versions:

https://github.com/vinci1it2000/formulas/blob/b3e03524e6a737ae83e683114edf289d95627ccc/setup.py#L119-L121
