### ISSUE TITLE
Error when parsing negative exponents

### ISSUE THREAD

**Issue by sanbales** [vinci1it2000/formulas#3]
Thank you for the quick response to my last issue.  And my apologies for sending another, but I am discovering these as I parse a large workbook.

Parsing `"=10^-2"` is also giving an error:

```
---------------------------------------------------------------------------
FormulaError                              Traceback (most recent call last)
<ipython-input-17-b1d71417b7f0> in <module>()
      4 parser = Parser()
      5 
----> 6 parser.ast(expression='=10^-2')

c:\sandboxes\excel2py\formulas\formulas\parser.py in ast(self, expression, context)
     54                     pass
     55             else:
---> 56                 raise FormulaError(expression)
     57         Parenthesis(')').ast(tokens, stack, builder)
     58         tokens = tokens[1:-1]

FormulaError: ('Not a valid formula:\n%s', '=10^-2')

> c:\sandboxes\excel2py\formulas\formulas\parser.py(56)ast()
     54                     pass
     55             else:
---> 56                 raise FormulaError(expression)
     57         Parenthesis(')').ast(tokens, stack, builder)
     58         tokens = tokens[1:-1]
```

Wrapping the negative exponent in parenthesis fixes the problem, but it can be a chore to go into the workbook and fix all the cases where there is a `X^-Y`.

I hope to put in a pull request with some of the pythonized Excel functions I have shortly.  I'll make sure to add tests and follow your convention.

**Comment by vinci1it2000** [comment]
I have fixed extending the regex expression of operators with [\*\/\^&<>=](?=\s*[\+\-]+).
