### ISSUE TITLE
Support an Apache License

### ISSUE THREAD

**Issue by jdbertron** [vinci1it2000/formulas#33]
Is there any chace you could support one of the Apache approved license (https://apache.org/legal/resolved.html#category-a)  instead of EUPL ?

**Comment by vinci1it2000** [comment]
Unfortunately, I cannot change the license. But you have two options:

1) The Apache license is one of the [upstream](https://joinup.ec.europa.eu/collection/eupl/eupl-compatible-open-source-licences) compatible licenses of the EUPL. Hence, the "derivative work" has to be redistributed under the EUPL. 

2) If you don't want to use the EUPL, you can use the functionality of `formulas` as it is (i.e., without merging the source code), following the example of chapter 5.6 of the [EUPL guidelines](https://joinup.ec.europa.eu/collection/eupl/guidelines-users-and-developers). Therefore, if you need extra functionalities, you can propose those through pull requests with the changes and/or the features that you want to integrate into `formulas`.

I hope that these links are helpful. If this is not sufficient, I can contact the legal service of the European Commission that can give a more exhaustive answer.
