### ISSUE TITLE
Named cells that start with a cell name format are not supported

### ISSUE THREAD

**Issue by dtorres-sf** [vinci1it2000/formulas#41]
**Describe the bug**
Named cells that start with a real cell name such as `CG2033_TEST` are not supported. The parser finds `CG2033` and `_TEST` as different portions when running through the `_re_range` regular expression. Other named cells that do not start with a regex that could be interpreted as a valid cell work fine.

**To Reproduce**
Simply name a cell `CG2033_TEST` and then in another cell enter the formula `=CG2033_TEST`. This works fine in excel, the second cell will always equal whatever the input is for the first cell. This fails in formulas. This **did** work in previous version 0.3. 

**Expected behavior**
Named cell is interpretted as a `ref` rather than a cell.

**Additional context**
I tried adjusting the regular expression in `operand.py` with many iterations. I was unable to get it to both work for the named cell case and normal cells. If you let me know which part of the regex I should update I am happy to give it a try. I was trying to get negative lookahead to rule out the case a cell name is followed by underscore or letter but couldn't get it to work.

**Comment by dtorres-sf** [comment]
@vinci1it2000 I am happy to help develop a fix and add tests if you point me in the right direction on how to edit the large regex in `operand.py`

**Comment by vinci1it2000** [comment]
You should try to add a negative lookahead expression (i.e., `(?![_\.])`) in [L115](https://github.com/vinci1it2000/formulas/blob/master/formulas/tokens/operand.py#L115) and [L128](https://github.com/vinci1it2000/formulas/blob/master/formulas/tokens/operand.py#L128) of the regular expression.

**Comment by vinci1it2000** [comment]
Done with 57f3922.
