### ISSUE TITLE
Saving Evaluated Excel workbook with formulas

### ISSUE THREAD

**Issue by Avik1993** [vinci1it2000/formulas#45]
**Is your feature request related to a problem? Please describe.**
I am looking to get the formulas stored along with the evaluated value in each cell for the saved files using `xl_model.write(dirpath=dir_output)`

**Describe the solution you'd like**
Currently only the evaluated value is getting stored in the new file but it would be really helpful to stored the formulas as well.

My use case is that user can again and again modify the excel sheet formulas and on each new save, I want to evaluate new values and replace the original file with updated formula / updated value in original file.

**Describe alternatives you've considered**
I am trying to implement something using formulas and `openpyxl` but would need some suggestions, how this could be implemented?

Much appreciated!

**Comment by mishu-** [comment]
+1

**Comment by vinci1it2000** [comment]
This is a [limitation](https://bitbucket.org/openpyxl/openpyxl/issues/1146/not-saving-formula-values) of `openpyxl` that does not allow to store the formulas along with the values. You can make a monkey-patch of `openpyxl` to store both.
