### ISSUE TITLE
How can you set a value to a cell - this is the very primitive function; the example given shows input and complicated way to set the value of a cell.

### ISSUE THREAD

**Issue by meyers007** [vinci1it2000/formulas#47]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by meyers007** [comment]
How can you set a value to a cell - this is the very primitive function; the example given shows input and complicated way to set the value of a cell.

The following is too messy;

### ```
xl_model.calculate(
    inputs={
        "'[EXCEL.XLSX]DATA'!A2": 3,  # To overwrite the default value.
        "'[EXCEL.XLSX]DATA'!B3": 2  # To impose a value to B3 cell.
    },
    outputs=[
       "'[EXCEL.XLSX]DATA'!C2", "'[EXCEL.XLSX]DATA'!C6"
    ] # To define the outputs that you want to calculate.
)
```


How can I just a value of cell something like:
         `xl_model['A1'] = 30 `

**Comment by vinci1it2000** [comment]
If you want just to set the cell's values without executing the formulas, I suggest using another library like `openpyxl`.
