### ISSUE TITLE
named ranges pointing to different workbooks exception not handled

### ISSUE THREAD

**Issue by simonschaluppe** [vinci1it2000/formulas#48]
**Describe the bug**
excel mode crashes when parsing named ranges that point to a different workbook

**To Reproduce**
add a named range pointing to a different workbook

**Expected behavior**
Raise an NotImplemented Error or something.

**Comment by vinci1it2000** [comment]
Can you provide a sample file?

**Comment by ernakulgoyal** [comment]
@vinci1it2000 I am exploring formulas but now stuck at the use of Named Ranges. Could you please share a working sample code to work with Named Ranges (defined in Name Manager/tables in excel). The documentation does not provide any information on how to use it. It would be really helpful.

**Comment by vinci1it2000** [comment]
Fixed in the 95f81e1 commit. Regarding the working example, you can use the excel [file](https://github.com/vinci1it2000/formulas/blob/master/test/test_files/test.xlsx) in the test folder.
