### ISSUE TITLE
Missing text cells from XLS

### ISSUE THREAD

**Issue by mishu-** [vinci1it2000/formulas#49]
When I run this excel: [test.xlsx](https://github.com/vinci1it2000/formulas/files/4719371/test.xlsx) I get the following output:
![image](https://user-images.githubusercontent.com/611429/83563390-b8bc2d80-a523-11ea-9d56-da5f29c6a609.png)
It's stripped of the first text in the column, basically it only keeps the values I gave in as input. Everything in column A is missing, B1 and B4 are also missing.
My code looks like this:
```
        xl_model = formulas.ExcelModel().loads(fpath).finish()
        wb = load_workbook(filename=options['file'][0])
        inputs = {
            #"'[TEST.XLSX]DATA'!B1": wb.worksheets[0]['B1'].value,
            "'[TEST.XLSX]DATA'!B2": wb.worksheets[0]['B2'].value,
            "'[TEST.XLSX]DATA'!B3": wb.worksheets[0]['B3'].value+"+B1",
            "'[TEST.XLSX]DATA'!B5": "=B1+B3",
            
        }
        solution = xl_model.calculate(inputs)
        xl_model.write(dirpath='output')
``` 
Extra weirdness: on other, more complicated test files I do get some text (but without the formatting, which is specified in another issue open on this repo)

What am I missing?

**Comment by vinci1it2000** [comment]
According to the excel file, the sheet name of the input data should be `SHEET1` instead of `DATA`. 

Moreover, I guess that you are trying to overwrite the functions in cells `B3` and `B5`. This is not possible from the `calculate` method, you can only pass the vaòue directly. If you want to modify the excel formulas, you can do the following:

```
# Load the excel file.
>>> xl_model = formulas.ExcelModel().loads('test.xlsx').finish()

# Define new formulas.
>>> new_formulas = {
...     "'[TEST.XLSX]SHEET1'!B3": "='[TEST.XLSX]SHEET1'!B1 + '[TEST.XLSX]SHEET1'!B2 + '[TEST.XLSX]SHEET1'!B1",
...     "'[TEST.XLSX]SHEET1'!B5": "='[TEST.XLSX]SHEET1'!B1 + '[TEST.XLSX]SHEET1'!B3"
... }

# Remove old formulas and default values. 
>>> dsp = xl_model.dsp
>>> for k in new_formulas:
...     dsp.dmap.remove_nodes_from(list(dsp.dmap.pred.get(k, [])))
...     dsp.default_values.pop(k, None)

# Add the new formulas.
>>> xl_model.from_dict(new_formulas)

# Calculate.
>>> solution = xl_model.calculate({"'[TEST.XLSX]SHEET1'!B1": 3})

# Write.
>>> xl_model.write(dirpath='output')
```
