### ISSUE TITLE
Error parsing functions with numbers in their name

### ISSUE THREAD

**Issue by sanbales** [vinci1it2000/formulas#5]
Looks like functions with numbers in their names cannot be parsed correctly, e.g., `ATAN2`, `DAYS360`.

Trying to parse a sheet with the equation `=ATAN2(10,2)` yields:

`FormulaError: ('Not a valid formula:\n%s', '=ATAN2(10,2)')`

**Comment by vinci1it2000** [comment]
The formula is captured as range. So I added a negative lookahead `(?!\()` to the regex expression of the range.
