### ISSUE TITLE
Spaces in sheets names

### ISSUE THREAD

**Issue by lfaucheux** [vinci1it2000/formulas#50]
Nice package!

One really simple question. What about space-contained sheets names ? I mean

```
>>> import formulas
>>> formulas.Parser().ast("=SUM(sheetname!A3)")[1].compile().inputs
OrderedDict([('SHEETNAME!A3', <Ranges>(SHEETNAME!A3))])
```
works fine. But,

```
>>> problematic = "'sheet name'!A3"
>>> formulas.Parser().ast(f"=SUM({problematic})")[1].compile().inputs
OrderedDict([('SHEET NAME!A3', None)])
                               ^^^^
```
don't. What's strange is that 
```
>>> formulas.Ranges().push(problematic)
<Ranges>(SHEET NAME!A3)
```
does the job for what I can tell.

**Comment by lfaucheux** [comment]
Another hack . In [builder.py at line 87](https://github.com/vinci1it2000/formulas/blob/master/formulas/builder.py#L87), I have replaced

```
            token.set_expr()
```
by
```
            tname = token.name
            if '[' not in tname and '!' in tname:
                s_, r_ = tname.split('!')
                tname  = f"'{s_}'!{r_}"                  
            token.attr['expr'] = tname
```

Only if `'[' not in tname` since it actually works for some reason when the external filepath is specified.

**Comment by vinci1it2000** [comment]
Thanks for your finding! The correction is close to your proposal.
