### ISSUE TITLE
Implement __xludf.DUMMYFUNCTION added to sheets exported from Google Sheets

### ISSUE THREAD

**Issue by aglim** [vinci1it2000/formulas#51]
**Is your feature request related to a problem? Please describe.**
Google Sheets-specific formulas in sheets exported to Excel are wrapped with `ISERROR(__xludf.DUMMYFUNCTION(original_formula), computed_value)` where `__xludf.DUMMYFUNCTION` is a non-existent formula that always gives an error resulting in returning the computed value.

As `__xludf.DUMMYFUNCTION` is not implemented yet, files with Google Sheets-specific formulas can't be handled by **formulas** raising `NotImplementedError` exception.

**Describe the solution you'd like**
Implement `__xludf.DUMMYFUNCTION` which always returns an error.

**Comment by aglim** [comment]
Workaround for now is to add function in runtime with

```
FUNCTIONS = formulas.get_functions()
FUNCTIONS["__XLUDF.DUMMYFUNCTION"] = lambda s: formulas.NAME
```

**Comment by vinci1it2000** [comment]
I implemented a function as described above.
