### ISSUE TITLE
Improvement on READ ME

### ISSUE THREAD

**Issue by rmorel** [vinci1it2000/formulas#53]
**Is your feature request related to a problem? Please describe.**
It would be better for newcommers to know how to install the dev version of the package to assist with testing

**Describe the solution you'd like**
Add something along these lines on the READ ME at [formulas homepage](https://github.com/vinci1it2000/formulas)

To install the development version of formulas you can use:

``pip install https://github.com/vinci1it2000/formulas/archive/dev.zip``

**Describe alternatives you've considered**
This is the easiest way that I found to install a branch version via pip. I tested it just now and it works just fine. You can find more suggestions [here](https://stackoverflow.com/questions/20101834/pip-install-from-git-repo-branch).

**Additional context**
This might help people to test and debug the package.

**Comment by vinci1it2000** [comment]
Done. Nice suggestion. Thanks!
