### ISSUE TITLE
ExcelModel class in excel\__init__.py means it cannot be found by pyinstaller

### ISSUE THREAD

**Issue by Anti-Widdershins** [vinci1it2000/formulas#54]
The structure of formulas\excel module seems to be prohibiting building of an exe (at least with pyinstaller on Windows).
The ExcelModel class is in excel\__init__.py rather than in a file ExcelModel or similar.
This structure seems to cause a blindspot for pyinstaller, whereas VSCode can import ExcelModel.
Attempts with alternative importation statements, such as "from formulas.excel.__init__ import ExcelModel" seem to work in both the VSCode IDE and pyinstaller (according to the latter's diagnostics), but the relative import paths in ExcelModel (such as ..ranges) fail in pyinstaller because of the bizarre import path used.
Attempts at using --hidden-import= workarounds on the pyinstaller command line do not fix the problem either.

To reproduce, use one of the import statement formats mentioned below, instantiate ExcelModel from formulas, open a file & worksheet and call the calculate method.
This functions correctly in VSCode.
Attempt to build a Windows exe using pyinstaller.
Run. (A console build is best to see errors). ModuleNotFound... (the module concerned depends on which import statement was used.)

When using: import formulas statement...
Exception in ... No module named 'formulas.functions.info'
Exception in ... object has no attribute 'calculate'

When using: from formulas.excel.__init__ import ExcelModel statement...
File "site-packages\formulas\excel\__init__.py", line 29, in <module>
ModuleNotFoundError: No module named 'formulas.excel.ranges'

Pyinstaller should be assisted/allowed to find class ExcelModel, or at least recognise that it is in module formulas.excel and the relative-path import statements inside formulas\excel files should resolve correctly in an executable created by pyinstaller.

I have passed the same info to the pyinstaller forum, https://groups.google.com/forum/#!forum/pyinstaller . 
See subject containing 'formulas' and 'pyinstaller'.
My impression is that there might be two problems - perhaps a structural issue in formulas and a blind spot in pyinstaller relating to classes defined in __init__.py files .

 - OS: Windows 10
 - Python 3.8
 - formulas 1.0.0
- pyinstaller 3.6

**Comment by Anti-Widdershins** [comment]
Sorry, some of the file paths have been interpreted as containing control characters in my submission.
Where init (double-ended with two underscores) is in italics, it should be preceded by excel backslash.
I'll try again in quotes: "excel\__init__.py", or with a double backslash... "excel\\__init__.py"

**Comment by vinci1it2000** [comment]
Have you configured a hook file for formulas and schedula?

**Comment by Anti-Widdershins** [comment]
Thanks for that.
A pyinstaller hook file (just for formulas) seems to do the trick. The pyinstaller xref info doesn't seem to have changed so I don't know what magic is going on behind the scenes.

from PyInstaller.utils.hooks import collect_all


datas, binaries, hiddenimports = collect_all('formulas')

All good.
Thanks.

**Comment by mberdyshev** [comment]
Today I've faced the same problem. I managed to overcome it with the following hook:
```python
from PyInstaller.utils.hooks import collect_submodules

hiddenimports = collect_submodules("formulas.functions")
```
Or via cmd argument: `--collect-submodules formulas.functions`.
