### ISSUE TITLE
Is Excel IFS() implemented? General cell return value is #NAME?

### ISSUE THREAD

**Issue by Anti-Widdershins** [vinci1it2000/formulas#55]
The Excel function IFS() appears to be not implemented, but this is not reported unless the IFS expression is very simple. If IFS() is actually not implemented then please consider this a feature request. Alternatively, please consider this a bug report.
Thanks.

The cases that I am seeing are:
import formulas as fs
…
            ocell = “’[FILENAME]SHEETNAME’!J11”
            xl_model = fs.ExcelModel().loads(filename).finish()
            soln = xl_model.calculate(outputs=[ocell])
            result = soln[ocell].value[0][0]
            print(str(result))

if cell J11 contents are any of:
=IFS(G11<=100,"FIRST",G11<=150,"SECOND")
=IFS(G11<=100,"FIRST",G11<=150,"SECOND",G11<=180,"THIRD")
Then the returned value is:
#NAME?
which is of type: <class 'formulas.tokens.operand.XlError'>

If the =IFS expression is simplified down to:
=IFS(TRUE,"TRUE")
Then a NotImplementedError exception results:
Failed DISPATCHING '_xlfn.IFS' due to:
  NotImplementedError()
Traceback (most recent call last):
  File "C:\Users\widde\AppData\Local\Programs\Python\Python38\lib\site-packages\schedula\utils\sol.py", line 631, in _evaluate_node
    value = self._evaluate_function(args, node_id, node_attr, attr,
  File "C:\Users\widde\AppData\Local\Programs\Python\Python38\lib\site-packages\schedula\utils\sol.py", line 604, in _evaluate_function
    res = async_process(
  File "C:\Users\widde\AppData\Local\Programs\Python\Python38\lib\site-packages\schedula\utils\asy\__init__.py", line 177, in async_process
    res = (exe and exe.process_funcs or _process_funcs)(
  File "C:\Users\widde\AppData\Local\Programs\Python\Python38\lib\site-packages\schedula\utils\asy\__init__.py", line 135, in _process_funcs
    r['res'] = e.process(sid, fn, *args, **kw) if e else fn(*args, **kw)
  File "C:\Users\widde\AppData\Local\Programs\Python\Python38\lib\site-packages\formulas\functions\__init__.py", line 98, in not_implemented
    raise NotImplementedError
NotImplementedError

By contrast, with an =IF function:
=IF(TRUE,"TRUE","FALSE")
The reported result is:
TRUE

**Comment by Anti-Widdershins** [comment]
I've had a bit of a closer look and I see that IFS is not implemented.
I'll have a look into formulas and see if I'm capable of implementing IFS myself (a learning exercise for sure).
However, I don't yet know if formulas can support a variable numbers of parameters in Excel commands: In the versions of Excel where it is supported, apparently IFS can accept between 1 and 127 test and value pairs.

**Comment by Anti-Widdershins** [comment]
I've implemented IFS(), merged on the dev branch HEAD, and submitted a pull request for the upgrade.
I've found the formulas package to be immensely useful and also educational.

Please accept my apologies for any failures of etiquette regarding my pull request. I'm new to both python and Github.

One of the IFS tests in sheet LOGIC of text.xlsx (cell AF8) has brought up the issue of Excel 2016's complex handling of '@' and SINGLE operator/function. It looks like openpyxl might drop '@' operators (needs further study) and Excel 2016 converts some '@' operators to SINGLE (as read by openpyxl) but still displays '@' in the cell.
I've currently created a SINGLE() function in LOGIC that only generates #VALUE! errors so as to pass the IFS cell AF8 test.
To support '@' and SINGLE, I think that the wrappers would have to pass the current cell's address for comparison and presumably openpyxl and token parsing for '@' would have to be introduced. 
I'm not sure of the merits of implementation.

I've also had to make some tweaks to the OR() Excel function support in xand() to match the error response to that of Excel 2016: Specifically, a #REF! error in any input parameter creates a #REF! output regardless of whether the erroneous parameter needs to be parsed & evaluated to generate a valid logical result.

I've saved all of the test Excel files in Excel 2016 format.

John Brook

**Comment by vinci1it2000** [comment]
Response in https://github.com/vinci1it2000/formulas/pull/57#issuecomment-780100309.
