### ISSUE TITLE
Not valid formula '=IF(A1>=-1,1,0)'

### ISSUE THREAD

**Issue by vasyafon** [vinci1it2000/formulas#58]
**Describe the bug**

The formula looks valid and is valid in LibreOffice Calc 6.4.4.2
if the sign '>=' is replaced to '>' or to '=' the formula turns to be validated.

**To Reproduce**

import formulas
formulas.Parser().ast('=IF(A1>=-1,1,0)')

>formulas.errors.FormulaError: ('Not a valid formula:\n%s', '=IF(A1>=-2,1,0)')

**Desktop (please complete the following information):**
 - OS: Ubuntu 20.04
 - Python 3.8.2
 - Version  formulas-1.0.0

**Comment by vinci1it2000** [comment]
Done!
