### ISSUE TITLE
SUM Function Errors if input is a string

### ISSUE THREAD

**Issue by widgetdude** [vinci1it2000/formulas#59]
**Describe the bug**
The SUM function returns a #VALUE! error if the number is passed in as a string.  

**To Reproduce**
```
formula = "=SUM( HEADER_FLOW_USED )"
 var_values = {
        "HEADER_FLOW_USED": [
                "1094.5729399720826",
                "123.4567896654",
            ]
 }
func = formulas.Parser().ast(formula)[1].compile()
func_value = func(**var_values)
```

See above

**Expected behavior**
I expected that the function would recognize that the string being passed in is parseable to a float and could be summed

**Screenshots**

**Desktop (please complete the following information):**

**Additional context**

**Comment by vinci1it2000** [comment]
Done! You can use my dev.
