### ISSUE TITLE
Examples?

### ISSUE THREAD

**Issue by jimlynnjulian** [vinci1it2000/formulas#6]
Hello,

   Thank you for your software.
   I could slog through the API, but I have only two long astronomy formulas to convert from excel to python.
   A couple of examples would help new users.

**Comment by jimlynnjulian** [comment]
I decided to slog through the translation.

**Comment by vinci1it2000** [comment]
An example how to parse and execute an excel formula is the following:
     
        >>> import formulas
        >>> func = formulas.Parser().ast('=(1 + 1) + (A1 + B3) / A2')[1].compile()

To visualize formula model and get the input order you can do the following:

       >>> func.inputs
       OrderedDict([('A1', <Ranges>(A1)), ('A2', <Ranges>(A2)), ('B3', <Ranges>(B3))])
       >>> func.plot()

![image](https://user-images.githubusercontent.com/11716821/32787131-19c6ca06-c956-11e7-90e5-708fe4abb6c7.png)

Finally to execute the formula and plot the workflow:
 
       >>> func(0, 1, 5)
       7.0
       >>> func.plot(workflow=True)

![image](https://user-images.githubusercontent.com/11716821/32788096-9d944492-c958-11e7-9530-3ce26fd1e1fb.png)

**Comment by vinci1it2000** [comment]
Some basic example has been added to the documentation.
