### ISSUE TITLE
Cells with multiple line breaks in a row

### ISSUE THREAD

**Issue by done712** [vinci1it2000/formulas#61]
Package cannot handle cells with formulas that include multiple line breaks in a row, i.e. in my excel file there is a cell with the following content:

> =IF(
>
> A1=1;
>
> 1;
>
> 2 )

The error that is raised is:

> formulas.errors.FormulaError: ('Not a valid formula:\n%s', '=IF(\n\nA1=1,\n\n1,\n\n2)')

**Comment by vinci1it2000** [comment]
Done!

**Comment by done712** [comment]
Just had a short look at your code change - what if I have a formula like this: ="\n" & SUM(3,4)
Wouldn't the \n (=string) also be replaced (which would not be the desired outcome)? Then again I don't know the structure of your package well enough.

**Comment by vinci1it2000** [comment]
This is not an issue because `\n` is a special character. The formula `="\n" & SUM(3,4)` is seeing by python as `"\\n" & SUM(3,4)`.
