### ISSUE TITLE
Invalid formula

### ISSUE THREAD

**Issue by cc-a** [vinci1it2000/formulas#63]
**Describe the bug**

`FormulaError` is raised when parsing a spreadsheet containing a formula of the form `=A1 =+B1`.

Trivial variations of this formula parse correctly, e.g. `=A1 =B1` and `=A1=+B1`

**To Reproduce**

The workbook [invalid_formula.xlsx](https://github.com/vinci1it2000/formulas/files/5725390/invalid_formula.xlsx) can be loaded to reproduce.

**Expected behavior**
The formula is valid in Excel so should be parsed correctly.

**Desktop (please complete the following information):**
 - OS: Arch Linux
 - Version: N/A

**Additional context**
N/A

**Comment by vinci1it2000** [comment]
This issue is solved. You can use my dev. Thanks for your finding!
