### ISSUE TITLE
Openpyxml InvalidFileException

### ISSUE THREAD

**Issue by amankagarwal** [vinci1it2000/formulas#64]
**Describe the bug**

Trying to load a model, and keep getting this error. I am able to open the file when I open it from finder. Tried saving it as a xlsm, open strict xml, but neither works. This error is thrown after a few minutes of execution.

`FormulasTesting/venv/lib/python3.9/site-packages/openpyxl/worksheet/_reader.py:300: UserWarning: Data Validation extension is not supported and will be removed
  warn(msg)
Traceback (most recent call last):
  File "/FormulasTesting/main.py", line 20, in <module>
    do()
  File "/FormulasTesting/main.py", line 12, in do
    xl_model = formulas.ExcelModel().loads(fpath).finish()
  File "/FormulasTesting/venv/lib/python3.9/site-packages/formulas/excel/__init__.py", line 243, in finish
    self.complete()
  File "/FormulasTesting/venv/lib/python3.9/site-packages/formulas/excel/__init__.py", line 232, in complete
    context = self.add_book(book)[1]
  File "/FormulasTesting/venv/lib/python3.9/site-packages/formulas/excel/__init__.py", line 132, in add_book
    data[BOOK] = book = load_workbook(fpath, data_only=data_only)
  File "/FormulasTesting/venv/lib/python3.9/site-packages/formulas/excel/xlreader.py", line 28, in load_workbook
    reader = XlReader(filename, **kw)
  File "/FormulasTesting/venv/lib/python3.9/site-packages/formulas/excel/xlreader.py", line 17, in __init__
    super(XlReader, self).__init__(*args, **kwargs)
  File "/FormulasTesting/venv/lib/python3.9/site-packages/openpyxl/reader/excel.py", line 124, in __init__
    self.archive = _validate_archive(fn)
  File "/FormulasTesting/venv/lib/python3.9/site-packages/openpyxl/reader/excel.py", line 94, in _validate_archive
    raise InvalidFileException(msg)
openpyxl.utils.exceptions.InvalidFileException: openpyxl does not support  file format, please check you can open it with Excel first. Supported formats are: .xlsx,.xlsm,.xltx,.xltm
`

Maybe this is a question for openpyxl, but wanted to check here if anyone has any inputs. Not sure if this is re-producible, might be specific to the specific excel file I am using.

**Expected behavior**
Able to load the xlsx file successfully.

**Desktop (please complete the following information):**
 - OS: iOS
 - Version 10.15.6

**Comment by amankagarwal** [comment]
I tried using load_workbook with the same file directly, and it returns me a Workbook object. Not sure if I am doing something wrong when doing `xl_model = formulas.ExcelModel().loads(fpath).finish()`

**Comment by vinci1it2000** [comment]
Can you share a copy of the file?

**Comment by amankagarwal** [comment]
Unfortunately can't since it has some sensitive data. was wondering if you have any tips on debugging it- somehow works well with Pycel but want to give formulas a shot

**Comment by vinci1it2000** [comment]
I found the reason. 

You have a reference inside the `.xlsx` file pointing to another excel with a different format, i.e., a relative link like `='[OTHER.XLS]SHEET1'!A1`. 

You can use my dev (`pip install https://github.com/vinci1it2000/formulas/archive/dev.zip`) to find the "corrupted" file. Then, you have two options:
1. replace the relative link with a `.xlsx` file (RECOMMENDED).
2. continue using my dev that replaces the links to the corrupted files with `#REF!`.

Let me know if this solves your problem.

**Comment by amankagarwal** [comment]
@vinci1it2000 thanks for the reply, how do I go about finding this corrupted file? Not sure what to do using the dev you linked. My excel is huge and to my knowledge there should be no links to external files.

**Comment by vinci1it2000** [comment]
when you execute your script using my dev, `formulas` will [log](https://github.com/vinci1it2000/formulas/blob/dev/formulas/excel/__init__.py#L243) a warning that tells you which equation couldn't be loaded.
