### ISSUE TITLE
Specifying Model Outputs

### ISSUE THREAD

**Issue by cc-a** [vinci1it2000/formulas#65]
**Is your feature request related to a problem? Please describe.**

We have encountered performance issues when attempting to use Formulas with complex spreadsheets ~14MB in size. Finishing time was at several days and still not completed.

**Describe the solution you'd like**

The ability to limit construction of the execution graph based on specified output cells/named ranges. From use of other libraries (e.g. [excel_to_code](https://github.com/tamc/excel_to_code/)) we've found this to be a key approach to reduce parsing times.

**Describe alternatives you've considered**

A considerable amount of work to manually prune unnecessary parts of the spreadsheet but this is not a flexible or scalable approach.

**Additional context**

I'm enquiring on behalf of a research group at Imperial College London. We are interested in this functionality to explore the use of Formulas in an on-going project. We may be able to implement this functionality (our guess is that it should be fairly simple) if you can recommend an approach and point us to where to get started.

**Comment by cc-a** [comment]
Hiya. Any thoughts on this? We're hoping to be able to start work on this soon so any guidance you're able to provide would be much appreciated.

**Comment by vinci1it2000** [comment]
Sorry I did a typo in the commit message. Anyhow, you can try my dev, I did some changes to improve the reading performances. I added a method `load_from_range` to the `ExcelModel`. An example of usage is documented in the [readme](https://github.com/vinci1it2000/formulas/blame/dev/README.rst#L192-L212).

**Comment by cc-a** [comment]
Wow, thank you for this! I will take a look how this performs with our models.

**Comment by cc-a** [comment]
Thanks very much for this, just picking it up now. Hitting an immediate issue with this functionality and named ranges. I infer from [ranges.py](https://github.com/vinci1it2000/formulas/blob/b13bcb8a4e29d6d6dd7779815a50a3ce6d060ac3/formulas/ranges.py#L161-L162) that these are not just not supported. Any suggestions on how to proceed?

**Comment by vinci1it2000** [comment]
The named ranges are supported by the library. The highlighted lines are used when the named range is not resolved, i.e. when it is missing the referenced file.
