### ISSUE TITLE
Now() and Rand() should not cache their values at parsing stage

### ISSUE THREAD

**Issue by trinetra75** [vinci1it2000/formulas#67]
The package does not properly support impure functions at the parsing stage.
[Impure function are those whose result does not depend only from the listed inputs, but also from some hidden state the function has access to]
 
A couple of those functions in excel are `now()` and `rand()`, whose result is supposed to change each time they are executed, even if they have no arguments at all, where as, in **formulas**, they get evaluated once at the parsing stage and their value is cached, so they will yield always the same result through all the execution(s) of the sheet.
 
This implies that formulas is not fully consistent with excel regarding these functions.
 
It would be good to introduce a new function attribute [in excel it is called _volatile_] that excludes a function from trying to cache its values during parsing, while keeping it in the list of functions to execute as normal.
[This is essentially the same behaviour associated with a function that has arguments depending on other cells]

**Comment by vinci1it2000** [comment]
Fixed with 64f392b commit.

**Comment by trinetra75** [comment]
Please re-open this issue: we found a probable bug:

Attached is a simple sheet that uses RAND() on a bunch of cells and then on cell C22 we take their Sum, but C22 does not appear in the _formulas_ results.

[range_bug.xlsx](https://github.com/vinci1it2000/formulas/files/6010992/range_bug.xlsx)

Here is the python script used to run the sheet.

-----------------------------------------

import os
import formulas
import collections
from formulas.functions import wrap_impure_func ,wrap_func, COMPILING
dir_input = ...

xlsxl_path = os.path.join(dir_input,range_bug.xlsx')
xl_model = formulas.ExcelModel().loads(xlsxl_path)
sol = xl_model.calculate()
print(sol)

---------------------

And here are our results that do not contain mentions about the cells C22 '=SUM(C7:C8)'

Solution([("'[range_bug.xlsx]RAND'!B22", <Ranges>('[range_bug.xlsx]RAND'!B22)=[['Average']]), ("'[range_bug.xlsx]RAND'!B5", <Ranges>('[range_bug.xlsx]RAND'!B5)=[['Num faces']]), ("'[range_bug.xlsx]RAND'!B7", <Ranges>('[range_bug.xlsx]RAND'!B7)=[['Samples']]), ("'[range_bug.xlsx]RAND'!C5", <Ranges>('[range_bug.xlsx]RAND'!C5)=[[6]]), ("'[range_bug.xlsx]RAND'!C10", <Ranges>('[range_bug.xlsx]RAND'!C10)=[[5.0]]), ("'[range_bug.xlsx]RAND'!C11", <Ranges>('[range_bug.xlsx]RAND'!C11)=[[5.0]]), ("'[range_bug.xlsx]RAND'!C7", <Ranges>('[range_bug.xlsx]RAND'!C7)=[[2.0]]), ("'[range_bug.xlsx]RAND'!C8", <Ranges>('[range_bug.xlsx]RAND'!C8)=[[3.0]]), ("'[range_bug.xlsx]RAND'!C9", <Ranges>('[range_bug.xlsx]RAND'!C9)=[[3.0]])])

**Comment by vinci1it2000** [comment]
I check the file and your script. You forgot to invoke the method `finish` of the ExcelModel. You can correct it as follow:

```
xl_model = formulas.ExcelModel().loads(xlsxl_path).finish()
```
