### ISSUE TITLE
More usage documentation

### ISSUE THREAD

**Issue by mgerring** [vinci1it2000/formulas#7]
Hi @vinci1it2000, I'm looking to integrate this library into [CJ Workbench](https://github.com/CJWorkbench/cjworkbench) and I could use some help understanding all of the pieces. 

In our case we need to be able to both convert Excel formulas to Python functions, and select data in a Pandas dataframe based on the provided range to provide it to the function.

We would be happy to contribute back documentation, examples and Excel formulas that are currently missing from this library if you could give us some help understanding it.

**Comment by mgerring** [comment]
@vinci1it2000 great! Not sure how to do private messages on here, go ahead and email me at gerring.matthew at gmail.com

**Comment by vinci1it2000** [comment]
I’m closing this issue, because there should be enough examples to solve the problem that you have described. If not please reopen it and I’ll respond to your follow up questions.
