### ISSUE TITLE
FormulaError with % operator preceded by space

### ISSUE THREAD

**Issue by cc-a** [vinci1it2000/formulas#70]
**Describe the bug**
Valid formulas such as `=A1 %` cause a FormulaError whilst `=A1%` does not.

**To Reproduce**
Simple example spreadsheet attached. Run `model = formulas.ExcelModel().loads("percentage_test.xlsx").finish()`

[percentage_test.xlsx](https://github.com/vinci1it2000/formulas/files/6090249/percentage_test.xlsx)

**Expected behavior**
Formulas should be parsed correctly.

**Desktop (please complete the following information):**
 - OS: Arch Linux
 - Version: N/A

**Comment by vinci1it2000** [comment]
Thanks for your finding. I fixed the bug. You can use my dev.
