### ISSUE TITLE
Formulas hangs on opening file with full-range formulas 

### ISSUE THREAD

**Issue by aglim** [vinci1it2000/formulas#73]
I have run into issue with full-range formulas like =SUM(A:A). 

Formulas hangs in finish() method forever when loading attached example file:

`xl_model = formulas.ExcelModel().loads("01.xlsx").finish() `

[01.xlsx](https://github.com/vinci1it2000/formulas/files/6243860/01.xlsx)

(Now I am using this [gist ](https://gist.github.com/aaronchall/6331661fe0185c30a0b4)to set timeout for inputs like this)

**Comment by vinci1it2000** [comment]
The new release improves the performance for parsing full ranges from 23 secs to about 3 secs.
