### ISSUE TITLE
From_ranges error

### ISSUE THREAD

**Issue by irene1014** [vinci1it2000/formulas#76]
**Describe the bug**
From_ranges function does not print values if the cell includes None.
For instance, if the cell A1 is None, B1 is 10 and C1 is =A1+B1, the value of c1 is 10. However, the output value from 'from_ranges' function is only B1 and the function does not print out C1. 
When I read the whole sheet using "loads" function, it prints out the value of C1 well. 

**To Reproduce**
`fpath = 'sample.xlsx'
xl_model = f.ExcelModel().from_ranges("'[%s]Sheet1'!A1:B3" % fpath)
print(xl_model.calculate().values())`

**Screenshots**
![image](https://user-images.githubusercontent.com/43365401/115127719-955c6e80-9f8d-11eb-87ce-b0a24d4f8575.png)
![image](https://user-images.githubusercontent.com/43365401/115127704-6cd47480-9f8d-11eb-996a-4a3eaf26215a.png)

**Comment by vinci1it2000** [comment]
`from_ranges` method reads all cells required to calculate the specified range. Hence, you should specify the output range as follows:
```
xl_model = formulas.ExcelModel().from_ranges("'[%s]Sheet1'!C1:C3" % fpath).finish()
```
