### ISSUE TITLE
How can I overwrite inputs, and save the new model with output to json file?

### ISSUE THREAD

**Issue by jingxiaorobin** [vinci1it2000/formulas#77]
Maybe I haven't known your library well enough.   It seems with xl_model.calculate( input = {}), I can only overwrite the input temporarily, but not get the new result with the new input. Also It didn't change the xl_model itself and the output value didn't change at all. How I could save the new result   after I overwrite the input and then  re-calculate the model? 

Expected Result
With each overwriting a new list of inputs, I can reach  to the new output values.

Please see attach, I overwrite Sheet1!A1 from 1 to 4, but the value still show as 1 and export json file for SheetA1 is still 1.

What

<img width="635" alt="Annotation 2021-04-19 164524" src="https://user-images.githubusercontent.com/40260870/115301038-b14b4600-a12e-11eb-85d6-20dc18212cc4.png">

I tried xl_model.compile() but it seems it can not overwrite and recalculate the model with  input number

**Comment by vinci1it2000** [comment]
I saw your code and there is one mistake about the data name `"'[%s]Sheet1'!A1" % fpath`. The right data name is `"'[%s]SHEET1'!A1" % fpath`. 

I saw another issue that you load the file without invoking the `finish` method that check missing dependencies and builds the ranges functions. 

`xl_model = formulas.ExcelModel().loads(fpath).finish()` 

I hope that it is clear now.
