### ISSUE TITLE
numpy-financial not available

### ISSUE THREAD

**Issue by jimlynnjulian** [vinci1it2000/formulas#81]
I followed the instructions at pypi.org to install: pip install formulas[all]. The download was to a Raspberry Pi 3B+.
When the download finished, the following error was posted:

"Could not find a version that satisfies the requirement numpy-financial (from formulas[all]) (from versions: )
No matching distribution found for numpy-financial (from formulas[all])."

The pypi site listed numpy-financial 1.0.0. after a search.
What do I do next?

Thank you.

**Comment by vinci1it2000** [comment]
If you need the financial functions, you should upgrade the python version to at least 3.5 because it is required by `numpy-financial`. Otherwise, you can disregard the warning.

**Comment by jimlynnjulian** [comment]
Thanks. 
Initially, I had attempted an install with Python 2.7.16. Tried again with 3.7.3 and succeeded.
