### ISSUE TITLE
[DOC] Question about using named references in workbook

### ISSUE THREAD

**Issue by flotho** [vinci1it2000/formulas#82]
AFAICS, many named references patches have been provided.
yet I'm not finding a proper way to adress such cells with their name instead of a full reference `[file.xls]!A1` .
What is you recommandation for adressing such cells like `[file.xls]named_ref_of_the_cell` .
Additionnaly what is the proper way to push this kind of references in the solution ouptput to be able to find easily the solution.

Regards

**Comment by MAG-Florian-Chevalier** [comment]
Hello,

I've found out a way to to do that (might not be the best one but it's working) : 
`["'[your_file.xlsx]'!named_ref_of_the_cell"].value[0][0]`
The `value[0][0]` is used to get the excel value, else you only retrieve a Range object.

Regards

**Comment by vinci1it2000** [comment]
Now the named references can be used as input for the calculation instead before they were just an output.

**Comment by flotho** [comment]
a great thanks @vinci1it2000
