### ISSUE TITLE
[1.1.0] bug to compile file, cell with recursive if

### ISSUE THREAD

**Issue by gaelTorrecillas** [vinci1it2000/formulas#84]
**Describe the bug**
hello,

I used your lib since 08/2020 with version 1.0.0, nice job for it.

I just change my branch for 1.1.0 but my file, who run with vers 1.0.0 don't run with the latest version (same dev branch).

I have cell with 79 IF same IF(a,b,IF(b,c,IF(etc...
The version 1.0.0 can compile this file.
But the version to 1.1.0, the function compute raise error : 

Unreachable output-targets: {"'[TMPB47GK500.XLSX]DIMENSIONNEMENT'!S18"}
Available outputs: []

What do I do to fix it?

**To Reproduce**
Attach the input files to reproduce the error or the code to be launched.

Do you have an email address to send you the xlsx file?

1.xl_model = formulas.ExcelModel().loads(file.name).finish()
2.  func = xl_model.compile(inputs=input_line,outputs=output_line)
3. See error

**Desktop (please complete the following information):**
 - OS: Fedora
 - Version 33

**Additional context**
python : 3.7
formulas : 1.1.0

**Comment by gaelTorrecillas** [comment]
fixed : 
I remove .upper() on filename.
Thank you for your help @vinci1it2000 .

**Comment by vinci1it2000** [comment]
No problem and thanks for using formulas.
