### ISSUE TITLE
VLOOKUP operations

### ISSUE THREAD

**Issue by MAG-Florian-Chevalier** [vinci1it2000/formulas#85]
Hi,

I got an excel file with formulas that I try to read with your library. It's working great for most of them, but I got issues when it comes to operations on VLOOKUP. Here are the patterns of formulas which give me a #VALUE! error (and the formulas are working fine when I open the file with Excel or LibreOffice) : 
- =1/VLOOKUP("text_to_search";matrix;4;FALSE())
- =VLOOKUP("text_to_search";matrix;4;FALSE())/VLOOKUP("text_to_search";matrix;4;FALSE())
- =VLOOKUP("text_to_search";matrix;4;FALSE())+VLOOKUP("text_to_search";matrix;4;FALSE())
- =VLOOKUP("text_to_search";matrix;4;FALSE())-VLOOKUP("text_to_search";matrix;4;FALSE())

I tried to put one VLOOKUP in a cell (let's say E10 for example), the library interprets the E10 cell correctly, but then I tried the operation like 1/E10 in an other cell and I also got the #VALUE! error with the library.

Do you know a way to perform those operations ? I'm using the dev branch.

Regards,
Florian

**Comment by flotho** [comment]
maybe #83 could be the same concern regarding the proper way to handle vlookup.
regards

**Comment by MAG-Florian-Chevalier** [comment]
Looks like it was just an issue with data format, I make sure to use "." as decimal separator instead of "," and it now works.
I will close this issue right away.
By the way, thanks for the job you produced on this library !
