### ISSUE TITLE
NotImplementedError for (CORREL, MEDIAN, SLOPE, PRODUCT, PMT, PV, RATE, DATEDIF, WEEKDAY, WEEKNUM) functions

### ISSUE THREAD

**Issue by frmZtH** [vinci1it2000/formulas#87]
**Describe the bug**
It seems that the some functions do not seem to be supported.
Such as (CORREL, MEDIAN, SLOPE, PRODUCT, PMT, PV, RATE, DATEDIF, WEEKDAY, WEEKNUM).

**To Reproduce**
`func = formulas.Parser().ast('=MEDIAN(A1,A2,A3,A4)')[1].compile()`
`func(1, 2, 3, 4)`

**Expected behavior**
It should return value.

**Screenshots**
`raise NotImplementedError`
`NotImplementedError`
`During handling of the above exception, another exception occurred:`
`    raise DispatcherError(
schedula.utils.exc.DispatcherError: ("Failed DISPATCHING '%s' due to:\n  %r", 'MEDIAN', NotImplementedError())`

**Desktop (please complete the following information):**
 - OS: [Windows 10]
 - Version [1.1.0]

**Comment by sada1993** [comment]
Also noticed this with the ADDRESS function in excel.

**Comment by vinci1it2000** [comment]
```
>>> import formulas 
>>> func = formulas.Parser().ast('=MEDIAN(A1,A2,A3,A4)')[1].compile()
>>> func(1, 2, 3, 4)
2.5
```
