### ISSUE TITLE
Issue with parenthesis and logical operators

### ISSUE THREAD

**Issue by mageshkv** [vinci1it2000/formulas#89]
Trying to execute a excel formula with parenthesis and logical operators and not getting the desired results

**To Reproduce**
Attach the input files to reproduce the error or the code to be launched.

import formulas

B3=210000
B4=0
B13=210000

def cal_test(B3,B4,B13):
      func=formulas.parser().ast('=IF(OR(AND(B3>0,B4>0),B3>B13),0,MAX(B3,B4))')[1].compile()
      a =func(B3,B4,B13)
     return a

z=cal_test(B3,B4,B13)
print(z)

**Expected behavior**

Scenario 1
Input values
B3=210000
B4=0
B13=210000
Expected value is 210000 -> MAX(B3,B4). This works as expected.

Scenario 2
Input values
B3=0
B4=210000
B13=210000

Expected value is 210000 -> MAX(B3,B4) but actual value returned is zero. Issue.

**Screenshots**
for scenario 2, Expected value is 210000 -> MAX(B3,B4) but actual value returned is zero

**Desktop (please complete the following information):**
 - OS:Windows
 - 10

**Additional context**

**Comment by vinci1it2000** [comment]
Before invoking the compiled function you should check the inputs' order and use the right order of inputs.
```
>>> import formulas
>>> func=formulas.Parser().ast('=IF(OR(AND(B3>0,B4>0),B3>B13),0,MAX(B3,B4))')[1].compile()
>>> func.inputs
OrderedDict([('B13', <Ranges>(B13)),
             ('B3', <Ranges>(B3)),
             ('B4', <Ranges>(B4))])
>>> func(0, 210000, 210000)
Array(0, dtype=object)
>>> func.solution
Solution([('0', 0),
          ('B13', 0),
          ('B3', 210000),
          ('B4', 210000),
          ('(B3 > 0)', Array(True, dtype=object)),
          ('(B3 > B13)', Array(True, dtype=object)),
          ('(B4 > 0)', Array(True, dtype=object)),
          ('MAX(B3, B4)', 210000),
          ('AND((B3 > 0), (B4 > 0))', True),
          ('OR(AND((B3 > 0), (B4 > 0)), (B3 > B13))', True),
          ('IF(OR(AND((B3 > 0), (B4 > 0)), (B3 > B13)), 0, MAX(B3, B4))',
           Array(0, dtype=object))])
```
An alternative way is to invoke the function using kwargs as follows:
```
>>> func(B3=0, B4=210000, B13=210000)
Array(210000, dtype=object)
```
