### ISSUE TITLE
Example results #VALUE!

### ISSUE THREAD

**Issue by guedehippolyte** [vinci1it2000/formulas#91]
I execute the example but i got #VALUE!. Sorry for my english.

import formulas

func = formulas.Parser().ast('=(1 + 1) + B3 / A2')[1].compile()
print(func(1, 5))

What's wrong? I precise I have Python 3.10 if it's necessary

**Comment by vinci1it2000** [comment]
The python version generated the problem, but it is now solved with the current dev.
