### ISSUE TITLE
Save the model

### ISSUE THREAD

**Issue by Omidbadrr** [vinci1it2000/formulas#95]
Hi,
Is it possible to add a feature to save the "xl_model"  ( xl_model = formulas.ExcelModel().loads(fpath).finish() ) on a disk and only load it later on if we want to use it instead of running formulas.ExcelModel()

**Comment by vinci1it2000** [comment]
Yes sure. Follows a code example:

```
>>> import formulas
>>> import json
>>> xl_model = formulas.ExcelModel().load('excel.xlsx')
>>> with open('model.json', 'w') as f: 
...     json.dump(xl_model.to_dict(), f)
>>> xl_model = formulas.ExcelModel()
... with open('model.json') as f: 
...     xl_model.from_dict(json.load(f))
```
